# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0dc24f3a146c19cc1147b627a600f52362b647b09996468bf6e955f67a40687ff350342a604abda03777a3e281e80443e7f77b8396ff1414b0eaf357ccf463b8

test:
  secret_key_base: 6e4f64fc6faea5873ab40187b085aaadce389879304bd360135f464117ee2ff4d5bb6d875106b22d140e53d51b476c1d240dcf269c2ab0c96215f2aba4077516

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
